CREATE TABLE IF NOT EXISTS assets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    serial TEXT UNIQUE NOT NULL,
    mac TEXT,
    model TEXT,
    keyboard TEXT,
    mouse TEXT,
    monitor_left TEXT,
    monitor_right TEXT,
    power_adapter TEXT,
    vga TEXT,
    headset TEXT,
    location TEXT,
    sub_location TEXT,
    area TEXT,
    sub_area TEXT,
    qeid TEXT,
    pein TEXT,
    user TEXT,
    site TEXT,
    po_number TEXT,
    image TEXT,
    hpdm_hostname TEXT,
    tag_number TEXT,
    date_deployed TEXT,
    date_returned TEXT,
    warranty_start TEXT,
    warranty_end TEXT,
    status TEXT DEFAULT 'Deployed',
    date_added TEXT DEFAULT CURRENT_TIMESTAMP
);